server {
    listen 80;
    server_name _;

    location /pdflover/privacy {
        alias /usr/share/nginx/html/privacy.html;
        default_type text/html;
    }

    location /pdflover/terms {
        alias /usr/share/nginx/html/terms.html;
        default_type text/html;
    }
}
